[Proxy]

# ZOOM
support.zoom.us = trojan, support.zoom.us, 443, password=xox, tls=true, sni=xix.gosiwin122.workers.dev, ws=true, ws-path=/pyip=210.16.65.149, ws-headers=Host:xix.gosiwin122.workers.dev
# <<<<---------------[°xox°]--------------->>>> #
# NOICE
listen.noice.id = trojan, listen.noice.id, 443, password=xox, tls=true, sni=xix.gosiwin122.workers.dev, ws=true, ws-path=/pyip=210.16.65.149, ws-headers=Host:xix.gosiwin122.workers.dev
# <<<<---------------[°xox°]--------------->>>> #
# LINEFRIENDS
collection.linefriends.com = trojan, collection.linefriends.com, 443, password=xox, tls=true, sni=xix.gosiwin122.workers.dev, ws=true, ws-path=/pyip=210.16.65.149, ws-headers=Host:xix.gosiwin122.workers.dev
# <<<<---------------[°xox°]--------------->>>> #


[Proxy Group]
SelectGroup = select, support.zoom.us, listen.noice.id, collection.linefriends.com


[Rule]
FINAL,SelectGroup