[Proxy]

investor.fb.com = trojan, investor.fb.com, 443, password=xox, tls=true, sni=xix.gosiwin122.workers.dev, ws=true, ws-path=/pyip=34.143.159.175, ws-headers=Host:xix.gosiwin122.workers.dev
# <<<<---------------[°xox°]--------------->>>> #

[Proxy Group]
SelectGroup = select, investor.fb.com

[Rule]
FINAL,SelectGroup