[Proxy]

# ZOOM
support.zoom.us = trojan, support.zoom.us, 443, password=xox, tls=true, sni=xix.gosiwin122.workers.dev, ws=true, ws-path=/pyip=125.253.92.51, ws-headers=Host:xix.gosiwin122.workers.dev
# <<<<---------------[°xox°]--------------->>>> #


[Proxy Group]
SelectGroup = select, support.zoom.us


[Rule]
FINAL,SelectGroup